.TH "ROWS CSV-MERGE" "1" "30-Oct-2019" "0.4.2.dev0" "rows csv-merge Manual"
.SH NAME
rows\-csv-merge \- Lazily merge CSVs (even if the schemas...
.SH SYNOPSIS
.B rows csv-merge
[OPTIONS] SOURCES... DESTINATION
.SH DESCRIPTION
Lazily merge CSVs (even if the schemas differs)
.SH OPTIONS
.TP
\fB\-\-input\-encoding\fP TEXT
.PP
.TP
\fB\-\-output\-encoding\fP TEXT
.PP
.TP
\fB\-s,\fP \-\-strip
.PP
